# ISSUES ENCOUNTERED

- Dataset used is to large in quantity it messed up on the GitHub part when i tried to add and push it to the repository

- You can access the dataset by running the python script "kaggle_dataset.py" on the terminal.

